# Generated by Django 5.2.17 on 2026-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0004_demanda_fluxo_interacao_delete_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='fluxo',
            field=models.CharField(choices=[('SUPORTE', 'Suporte'), ('SOLICITANTE', 'Solicitante')], default='SUPORTE', max_length=20, null=True),
        ),
    ]
